---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    java_version: "17"
    docker_compose_version: "2.24.0"
    maven_version: "3.9.6"
    
  roles:
    - common
    - java
    - docker
    - maven
    - jenkins

  post_tasks:
    - name: Display completion message
      debug:
        msg: |
          Server Configuration Complete!
          Server: {{ inventory_hostname }}
          Environment: {{ environment }}
          
          Tools installed: Java {{ java_version }}, Maven {{ maven_version }}, Docker, Jenkins, Git