---
- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    owner: appuser
    group: appuser
    mode: '0755'
  loop:
    - /opt/app
    - /opt/app/logs
    - /opt/app/deployments

- name: Set up log rotation for application logs
  copy:
    content: |
      /opt/app/logs/*.log {
          daily
          missingok
          rotate 30
          compress
          delaycompress
          notifempty
          copytruncate
      }
    dest: /etc/logrotate.d/user-registration-app
    owner: root
    group: root
    mode: '0644'
  copy:
    content: |
      [Unit]
      Description=User Registration Microservice
      After=docker.service
      Requires=docker.service
      
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      User=appuser
      Group=appuser
      WorkingDirectory=/opt/app/source
      ExecStart=/usr/local/bin/docker-compose up -d
      ExecStop=/usr/local/bin/docker-compose down
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/user-registration-app.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Display setup completion message
  debug:
    msg: |
      Application setup completed!
      
      Application directory: /opt/app
      Source code: /opt/app/source  
      Logs: /opt/app/logs
      Config: /opt/app/config
      
      Ready for CI/CD deployment!
